version: '3.7'
networks:
  counting-votes-network:
    name: "counting-votes-network"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "app-zookeeper"
    networks:
      - "counting-votes-network"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "app-kafka"
    networks:
      - "counting-votes-network"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  web:
    build: .
    container_name: "app-counting-votes"
    networks:
      - "counting-votes-network"
